### ISSUE TITLE
RDB Username max length diffrent of documentation

### ISSUE THREAD

**Issue by rchallie** [scaleway/scaleway-sdk-go#1119]
Hi!
I tried to create a RDB Instance and set a `user_name` of 62 chars following the [documentation](https://developers.scaleway.com/en/products/rdb/api/#name-1c83bc).
I checked the code and found this comment that match the documentation:
https://github.com/scaleway/scaleway-sdk-go/blob/8068134321231201ef22ee34966536c769364732/api/rdb/v1/rdb_sdk.go#L1292
But `terraform apply` return this:
```
Error: scaleway-sdk-go: invalid argument(s): user_name does not respect constraint, user_name length must be between 1 and 32
```

Scaleway-sdk-go version: `v2.2.0`
Go version: `go1.17.6`
GOOS: `darwin`
GOARCH: `amd64`

**Comment by remyleone** [comment]
Hello, could you paste the smallest terraform snippet that reproduces your issue?

**Comment by Monitob** [comment]
Fixed on [1546](https://github.com/scaleway/scaleway-sdk-go/pull/1546). This was a documentation issue
