### ISSUE TITLE
ipv6 floating ips for elastic metal are not supported

### ISSUE THREAD

**Issue by dedene** [scaleway/scaleway-sdk-go#1405]
Both the cli as the terraform provider struggle with ipv6 addresses. I.e. `scw fip ip list` yields the error 

```
Scaleway-sdk-go: could not parse application/json response body: invalid IP address: 2001:bc8:1203:17f::/64
```

In the terraform provider I observe something linked to the same error, i.e.:

```
│ Error: scaleway-sdk-go: waiting for FlexibleIP failed: scaleway-sdk-go: could not parse application/json response body: invalid IP address: 2001:bc8:1203:17f::/64
```

I'm no specialist in Go, but maybe the schema at https://github.com/scaleway/scaleway-sdk-go/blob/592cf1cf6e45a4a5c536bc107237ea93fbfb8685/api/flexibleip/v1alpha1/flexibleip_sdk.go#L248 should also allow for IPv6 type addresses?

**Comment by Codelax** [comment]
`2001:bc8:1203:17f::/64` is a CIDR, so net.IP is the wrong type to store it. We're looking to fix generation.
