### ISSUE TITLE
Collecting Object Storage and Public Gateways resources

### ISSUE THREAD

**Issue by mlabouardy** [scaleway/scaleway-sdk-go#1559]
Hey there,

I'm one of the makers of [Komiser](https://github.com/tailwarden/komiser), we're building an open-source platform to help companies build their cloud inventory and uncover insights about their infrastructure (costs wasted, security threats, and compliance issues). We're supporting Scaleway as a provider (see [here](https://www.tailwarden.com/blog/manage-your-scaleway-resources-with-komiser)) and we've been using the official Go SDK to collect Scaleway resources and apparently the current implementation doesn't support the collection of the following resources:
- https://www.scaleway.com/fr/public-gateway/
- https://www.scaleway.com/en/object-storage/

Could you give us a hand in maintaining the Scaleway integration or sharing some docs on how to support the missing services in the SDK (we could leverage our Discord community to add the missing features) :)

**Comment by remyleone** [comment]
Hello for the public gateway use this package: https://github.com/scaleway/scaleway-sdk-go/tree/master/api/vpcgw/v1 
and for object storage it is using a S3 interface therefore you would need to use native aws SDK for it.

**Comment by mlabouardy** [comment]
@remyleone thanks a lot!
