### ISSUE TITLE
Scaleway SDK behind the proxy.

### ISSUE THREAD

**Issue by kinikiti** [scaleway/scaleway-sdk-go#1991]
Hello.

We are using External Secrets operator with Scaleway as a secret provider.
Kubernetes is behind the proxy.
Environment variables are set and other providers (like AWS) are using them without any issues.

But Scaleway ignores `HTTPS_PROXY` variable and trying to connect directly.

As I can see Scaleway SDK vesion:
`github.com/scaleway/scaleway-sdk-go v1.0.0-beta.22`

Based on what I see transport is not adding Proxy to it. Am I right and this is a bug?

**Comment by Codelax** [comment]
Hello, thanks for reporting. I made a change to use Go default http transport.
It should fix the issue. I will make a release after the merge but it will require a bump in external secrets
