### ISSUE TITLE
Flexible IP import is not implemented?

### ISSUE THREAD

**Issue by ilchub** [scaleway/scaleway-sdk-go#2246]
I'm trying to import my existing Flexible IPs into tfstate, which is seem to be possible, at least according to TF module documentation:
```
terraform import scaleway_flexible_ip.main fr-par-1/11111111-1111-1111-1111-111111111111
```

But when I try to perform my own import:
```
terraform import -var-file=".tfvars" "module.<my_module_name>.scaleway_flexible_ip.flexible-ip" "<my-region>/<flexible-ip-id>"
```

I'm getting the following output:
```
│ Error: scaleway-sdk-go: waiting for FlexibleIP failed: scaleway-sdk-go: http error 501 Not Implemented: unknown service
```

Am I doing something wrong, or is this feature is unsupported by the current(2.46.0 at the time of writing) provider version?

More verbose import log is attached(some values are censored).
[tf-import.log](https://github.com/user-attachments/files/17348469/tf-import.log)

**Comment by Codelax** [comment]
Hi, by looking at your logs, it appears that the terraform provider tries to import your Flexible IP from zone `pl-waw-1` which is not a valid zone for baremetal API.
Also I can read the CLI arguments:
```
2024-10-12T05:03:36.954+0300 [INFO]  CLI command args: []string{"import", "-var-file=.tfvars", "module.<flexible-ip-module-name>.scaleway_flexible_ip.flexible-ip", "pl-waw-1/<flexible-ip-id>"}
```

Were you importing from pl-waw-1 ?

Also, as this is a common issue. Don't mix up "Flexible IP" and "Instance IP".
The first one is for baremetal servers, the second one for Instances.

**Comment by ilchub** [comment]
Hi, thanks for responding to my call for helm :)

Just to omit possible misunderstandings, I'm not trying to use bare-metal API with the help of Terraform. I'm trying to import a flexible IP, assigned to a Compute VM, so no bare metal instances are involved in this import.

`pl-waw-1` might not be a proper region+zone for bare metal instances, but this is sure a proper region+zone for compute instances.

Regarding the terminology, I was referring to the naming in the Scaleway Web Console. IP addresses for compute instances are for sure called `Flexible IPs` there(please refer to the screenshot below):
![2024-10-16_18-25](https://github.com/user-attachments/assets/fb821a9f-f38e-4b6b-bc52-68627c53779c)

So just for me to understand, is it proper to use flexible IPs for compute VMs or should I resort to try importing my IPs as Instance IP resource type?

**Comment by Codelax** [comment]
The naming in Console is "Flexible IP" but terraform provider refers to it as [scaleway_instance_ip](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/resources/instance_ip).
Example usage:
```
resource "scaleway_instance_ip" "public_ip" {}

resource "scaleway_instance_server" "web" {
  type = "DEV1-S"
  image = "ubuntu_jammy"
  ip_id = scaleway_instance_ip.public_ip.id
}
```

Naming is this way as those are IPs created using Instance API. There currently is a different API for baremetal server IPs, this different API is called Flexible IP.
