### ISSUE TITLE
Having a default User agent settings

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-sdk-go#29]
It would be nice to have the default sdk having a specific user string to give the version of the sdk used, the language and so on.

**Comment by jerome-quere** [comment]
It's already done: 

https://github.com/scaleway/scaleway-sdk-go/blob/29930cd612eb2da9d210b818d2c3bc2b3ed7a7f1/scw/version.go#L6

The default userAgent can be override using the `WithUserAgent` option when the client is created.
https://github.com/scaleway/scaleway-sdk-go/blob/29930cd612eb2da9d210b818d2c3bc2b3ed7a7f1/scw/client_option.go#L43
