### ISSUE TITLE
Refactor logging of http requests to use an http.Transport 

### ISSUE THREAD

**Issue by remyleone** [scaleway/scaleway-sdk-go#637]
Refactor the logging in the SDK to use Transport for the logging.

Roundtripper can be used as a chained decorator upon an HTTP request that can implement logging, authentication management, header manipulation, ...
Beware to chain them in the right order to avoid a logging transport to leak credentials.

**Comment by Codelax** [comment]
Would be useful for terraform, as logging is made after response, we do not log requests that are caught by hashicorp retry transport
