### ISSUE TITLE
Support v2beta1 DNS API

### ISSUE THREAD

**Issue by azuenko** [scaleway/scaleway-sdk-go#754]
Hello,

Is there any plans bump the DNS API version to  `v2beta1` ? It appears the current API version `v2alpha2` does not support domains and zones scoped to a project.

I'm using [kubernetes-sigs/external-dns](https://github.com/kubernetes-sigs/external-dns) inside my k8s Kapsule cluster, and it does not see the domains and zone defined inside a project.

Many thanks!

**Comment by Sh4d1** [comment]
Hey ! v2beta1 is already available here https://github.com/scaleway/scaleway-sdk-go/tree/master/api/domain/v2beta1
And a PR is open on external dns to bump it : https://github.com/kubernetes-sigs/external-dns/pull/1938 :)
