### ISSUE TITLE
Feature Request: filter marketplace API

### ISSUE THREAD

**Issue by Sh4d1** [scaleway/scaleway-sdk-go#89]
Would be nice to be able to filter the marketplace results. Example instdead of listing all images and then looping through to find the right one, have the sdk do it instead?

**Comment by jerome-quere** [comment]
Is it what you are looking for ? 
https://github.com/scaleway/scaleway-sdk-go/blob/1423be403b927e51e22983d821eead7966af34cd/api/marketplace/v1/marketplace_utils.go#L47

NB: method signature is going to change but not the content

**Comment by Sh4d1** [comment]
Yep :+1:
